set(CMAKE_CXX_STANDARD 17) 
set(CMAKE_BUILD_TYPE Debug)
set(BUILD_TESTING ON)
set(BUILD_DOCS ON)

set(CMAKE_C_COMPILER gcc-14)
set(CMAKE_CXX_COMPILER g++-14)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -Wall -Werror")
