include_guard()

macro(cxx_api_docs)
    string(TOLOWER "${PROJECT_NAME}" _ncad_lc_name)
    set(_ncad_target "${_ncad_lc_name}_cxx_api")
    find_package(Doxygen REQUIRED)
    set(DOXYGEN_USE_MATHJAX "YES")
    set(DOXYGEN_MATHJAX_RELPATH "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5")
    doxygen_add_docs("${_ncad_target}" ${ARGV})
endmacro()