include_guard()

macro(cxx_api_docs)
    string(TOLOWER "${PROJECT_NAME}" _ncad_lc_name)
    set(_ncad_target "${_ncad_lc_name}_cxx_api")
    find_package(Doxygen REQUIRED)
    set(DOXYGEN_PREDEFINED "ENABLE_EIGEN_SUPPORT")
    set(DOXYGEN_MACRO_EXPANSION "YES")
    doxygen_add_docs("${_ncad_target}" ${ARGV})
endmacro()