name: Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  # Deploy Documentation
  deploy_dox:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     - uses: ssciwr/doxygen-install@v1
      - uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Build Doxygen Part
        run: |
          cmake -Bbuild -H. -GNinja -DONLY_BUILD_DOCS=ON -DDOCS_FAIL_ON_WARNING=ON
          cmake --build build --target sigma_cxx_api --parallel
        shell: bash
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build/html  