name: Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  # Deploy Documentation
  deploy_dox:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux Dependencies
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Build Doxygen Part
        run: |
          toolchain=${PWD}/.github/workflow_toolchains/gnu-12.cmake
          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}"
          cmake --build build --target sigma_cxx_api --parallel
        shell: bash
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build/html  