name: Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  # Deploy Documentation
  deploy_dox:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python
        uses: actions/setup-python@v5
      - name: Install Linux Dependencies
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Build Doxygen Part
        run: |
          toolchain_dir=${PWD}/.github/workflow_toolchains
          toolchain=${toolchain_dir}/test_base.cmake
          echo 'include('${toolchain_dir}'/gnu-11.cmake)' >> $toolchain

          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}"
          cmake --build build --target sigma_cxx_api --parallel
          mkdir docs/build
          mkdir docs/build/html
          mv build/html docs/build/html/sigma_cxx_api
        shell: bash
      - name: Build Sphinx Part
        run:  |
          cd docs
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          make html SPHINXOPTS="-W --keep-going -n"
        shell: bash
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./docs/build/html  