name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test C++ libraries.
  test_library:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gnu-11, gnu-12]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux Dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Install MacOS Dependencies
        if: contains(matrix.os, 'macos')
        run: |
          brew install doxygen ninja
      - name: Build and Test
        run: |
          toolchain_dir=${PWD}/.github/workflow_toolchains
          toolchain=${toolchain_dir}/test_base.cmake
          echo 'include('${toolchain_dir}'/${{matrix.compiler}}.cmake)' >> $toolchain

          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}"
          cmake --build build --parallel
          cd build
          ctest -VV
        shell: bash
