name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test C++ libraries.
  test_library:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gnu-11, gnu-12, clang-default]
        eigen: [ON]
        include:
          - os: ubuntu-latest
            compiler: gnu-12
            eigen: OFF
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux Dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Install MacOS Dependencies
        if: contains(matrix.os, 'macos')
        run: |
          brew install doxygen ninja
      - name: Build and Test
        run: |
          toolchain_dir=${PWD}/.github/workflow_toolchains
          toolchain=${toolchain_dir}/test_base.cmake
          echo 'include('${toolchain_dir}'/${{matrix.compiler}}.cmake)' >> $toolchain

          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}" -DENABLE_EIGEN_SUPPORT=${{matrix.eigen}}
          cmake --build build --parallel
          cd build
          ctest -VV
        shell: bash

  # Test Build of Documentation
  test_dox_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux Dependencies
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Build Doxygen Part
        run: |
          toolchain_dir=${PWD}/.github/workflow_toolchains
          toolchain=${toolchain_dir}/test_base.cmake
          echo 'include('${toolchain_dir}'/gnu-11.cmake)' >> $toolchain

          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}"
          cmake --build build --target sigma_cxx_api --parallel
        shell: bash