name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test C++ libraries.
  test_library:
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2022]
        eigen: [ON, OFF]
        include:
          - os: macos-15
            version: 15
            toolset: clang
            arch: aarch64
          - os: ubuntu-24.04
            version: 24.04
            toolset: gcc
            arch: x86
          - os: windows-2022
            version: 2022
            toolset: msvc
            arch: x86
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ssciwr/doxygen-install@v2
      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.89.0
          platform_version: ${{ matrix.version }}
          toolset: ${{ matrix.toolset }}
          arch: ${{ matrix.arch }}
      - name: Build and Test
        run: |
          toolchain=${PWD}/.github/workflow_toolchains/${{matrix.toolset}}.cmake
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake -DCMAKE_TOOLCHAIN_FILE="${toolchain}" -B "build" -G "Visual Studio 17 2022" -T host=x64 -A x64 -DENABLE_EIGEN_SUPPORT=${{matrix.eigen}}
          else
            cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE="${toolchain}" -DENABLE_EIGEN_SUPPORT=${{matrix.eigen}}
          fi
          cmake --build build --parallel
          cd build
          ctest -C Debug -T test -VV --no-tests=error
        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        shell: bash

  # Test Build of Documentation
  test_dox_build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ssciwr/doxygen-install@v1
      - name: Build Doxygen Part
        run: |
          cmake -Bbuild -H. -GNinja -DONLY_BUILD_DOCS=ON -DDOCS_FAIL_ON_WARNING=ON
          cmake --build build --target sigma_cxx_api --parallel
        shell: bash

  # Run pre-commit hooks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install and Run pre-commit
        run: |
          pip install -r requirements.txt
          pre-commit run --all-files
        shell: bash
