name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # Build and test C++ libraries.
  test_library:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux Dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y doxygen ninja-build
      - name: Install MacOS Dependencies
        if: contains(matrix.os, 'macos')
        run: |
          brew install doxygen ninja
      - name: Build and Test
        run: |
          cmake -Bbuild -H. -GNinja -DCMAKE_TOOLCHAIN_FILE=./.github/test_toolchain.cmake
          cmake --build build --parallel
          cd build
          ctest -VV
        shell: bash
